# Generated by Django 5.0 on 2024-02-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_nickname_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
