# Generated by Django 5.0 on 2024-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_publish',
            field=models.BooleanField(default=False),
        ),
    ]
