# Generated by Django 5.0 on 2024-02-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_thumbtext_post_thumbcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='src',
        ),
    ]
