# Generated by Django 5.0 on 2024-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image_postimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbContent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
