# Generated by Django 5.0 on 2024-07-26 18:41

from django.db import migrations, models
from django.db.models import Max

#initialize index to postImage
def reverse_set_index(apps, schema_editor):
    PostImage = apps.get_model('blog', 'PostImage')
    Post = apps.get_model('blog', 'Post')
    for post_image in PostImage.objects.all():
        post: Post = post_image.post
        max_index = PostImage.objects.filter(post=post, device_id=post_image.device_id).aggregate(Max('index'))['index__max'] or 0
        post_image.index = max_index + 1
        post_image.save()

def set_index(apps, schema_editor):
    PostImage = apps.get_model('blog', 'PostImage')
    for post_image in PostImage.objects.all():
        post_image.index = 0
        post_image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_addfield_name_hash'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postimage',
            name='unique_post_device_index',
        ),
        migrations.RunPython(set_index, reverse_set_index),
        migrations.AlterField(
            model_name='postimage',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='index',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='name_hash',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='postimage',
            constraint=models.UniqueConstraint(fields=('post', 'device_id', 'name_hash'), name='unique_post_device_name_hash'),
        ),
    ]
