# Generated by Django 5.0 on 2024-07-27 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_change_design_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extraSpan',
            field=models.IntegerField(choices=[(0, 'Default'), (-1, 'Narrow'), (1, 'Wide')], default=0),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post'),
        ),
    ]
