# Generated by Django 5.0 on 2024-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_extraspan_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbContent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbType',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Heading'), (3, 'Line')], default=3, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbContent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbType',
        ),
    ]
