# Generated by Django 5.0 on 2024-07-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_thumbcontent_alter_post_thumbtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='pages',
        ),
    ]
