# Generated by Django 5.0 on 2024-08-17 01:24

from django.db import migrations

def set_postupdatedat(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    PostUpdatedAt = apps.get_model('blog', 'PostUpdatedAt')
    for post in Post.objects.all():
        post_updated_at, created = PostUpdatedAt.objects.get_or_create(
            author=post.author,
            year=post.date.year,
            month=post.date.month
        )
        post_updated_at.updated_at = post.updated_at
        post_updated_at.save()

def reverse_set_postupdatedat(apps, schema_editor):
    PostUpdatedAt = apps.get_model('blog', 'PostUpdatedAt')
    PostUpdatedAt.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_postupdatedat'),
    ]

    operations = [
        migrations.RunPython(set_postupdatedat, reverse_set_postupdatedat),
    ]
