# Generated by Django 5.0 on 2024-08-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_set_postupdatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='name_hash',
            field=models.CharField(max_length=200),
        ),
    ]
