# Generated by Django 5.0 on 2024-08-25 05:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_postimage_name_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='src',
            field=models.ImageField(max_length=255, upload_to=blog.models.image_upload_to),
        ),
    ]
