# Generated by Django 5.0 on 2024-08-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nudge', '0002_alter_nudge_author_alter_persona_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nudge',
            old_name='pages',
            new_name='page',
        ),
    ]
