# Generated by Django 5.0 on 2024-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nudge', '0003_rename_pages_nudge_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudge',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (-1, 'Rejected')], default=0),
        ),
    ]
