# Generated by Django 5.0 on 2024-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nudge', '0004_nudge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nudge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
